# Generated by Django 4.0.6 on 2022-07-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='No Name', max_length=30)),
                ('post_title', models.CharField(default='No Title', max_length=80)),
                ('post_heading1', models.CharField(default='No Heading', max_length=200)),
                ('post_heading2', models.CharField(default='No heading', max_length=400)),
                ('post_heading3', models.CharField(default='No Heading', max_length=200)),
                ('post_dateTime', models.DateTimeField(auto_now_add=True)),
                ('post_thumbnail', models.ImageField(default='', upload_to='shop/pro_images')),
            ],
        ),
    ]
