# Generated by Django 4.0.6 on 2022-07-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_content1',
            field=models.CharField(default='No content', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_content2',
            field=models.CharField(default='No content', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_content3',
            field=models.CharField(default='No content', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_heading1',
            field=models.CharField(default='No Heading', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_heading2',
            field=models.CharField(default='No heading', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_heading3',
            field=models.CharField(default='No Heading', max_length=100),
        ),
    ]
